### ISSUE TITLE
Categories (Backend)

### ISSUE THREAD

**Issue by Laksheya** [Laksheya/hostelbuddy#6]
**Task Description**
- [ ] Create categories routes
- [ ] Write controller to get all categories list
- [ ] Also write a controller to add a category if not existed
